name: Integration Gold CI - Production

on:      
  workflow_call:
    inputs:
      service_port:
        required: true
        type: string
      servers:
        required: true
        type: string
      target_platform:    # arm or x86
        required: true
        type: string
      ecr_name:
        required: true
        type: string
      runner_vm:
        required: true
        type: string

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  building:
    name: Building project
    runs-on:
        labels: ${{inputs.runner_vm}}

    env:
      CI: true
      NPM_FINANZERO_SECRET: ${{secrets.NPM_FINANZERO_SECRET}}
      PORT: ${{inputs.service_port}}
    outputs:
      project_name: ${{ steps.building.outputs.project_name }}
      image_tag: ${{ steps.building.outputs.image_tag }}
      image_name: ${{ steps.building.outputs.image_name }}
      port: ${{steps.building.outputs.port}}

    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Describe commit ID
        id: describe-commit-id
        run: |
          echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Building and Uploading Docker Image to ECR
        id: building
        run: |          
          export PROJECT_NAME=${PROJECT_NAME:-`basename "$PWD"`}
          export IMAGE_TAG=${IMAGE_TAG:-"local-`git rev-parse --short HEAD`"}
          export NPM_FINANZERO_SECRET=${NPM_FINANZERO_SECRET:-"$(cat ~/.npmrc)"}
          export IMAGE_NAME=`aws ecr describe-repositories --repository-names $PROJECT_NAME --output text --region sa-east-1 --query 'repositories[*].repositoryUri'`
          echo "project_name=$PROJECT_NAME" >> "$GITHUB_OUTPUT"
          echo "port=$PORT" >> "$GITHUB_OUTPUT"
          echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
          echo "current version=${{steps.package-version.outputs.current-version}}"
          echo "current commit=$COMMIT_ID"

          docker buildx build --build-arg NPM_RC="$NPM_FINANZERO_SECRET" \
              --build-arg VERSION_ID=${{steps.package-version.outputs.current-version}} \
              --build-arg COMMIT_ID=$COMMIT_ID \
              -t $PROJECT_NAME:${{inputs.target_platform}}-$IMAGE_TAG \
              -t $PROJECT_NAME:${{inputs.target_platform}}-latest \
              -f ./Dockerfile_beta .
              
          aws ecr create-repository --region sa-east-1 --repository-name ${PROJECT_NAME} >& /dev/null || echo 'Image repository already exists on aws (probably)'
          aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin ${{inputs.ecr_name}}
          
          docker image tag $PROJECT_NAME:${{inputs.target_platform}}-latest $IMAGE_NAME:${{inputs.target_platform}}-latest
          docker image tag $PROJECT_NAME:${{inputs.target_platform}}-latest $IMAGE_NAME:${{inputs.target_platform}}-$IMAGE_TAG
          docker image push $IMAGE_NAME:${{inputs.target_platform}}-latest
          docker image push $IMAGE_NAME:${{inputs.target_platform}}-$IMAGE_TAG
          
          echo "################# Uploaded docker image to AWS ##################"
          echo "Pushed image $IMAGE_NAME:${{inputs.target_platform}}-latest"
          echo "Pushed image $IMAGE_NAME:${{inputs.target_platform}}-$IMAGE_TAG"
          
          if [[ ${{contains( github.event.pull_request.labels.*.name, 'skip-deploy')}} = 'true' ]]; then
            docker image tag $PROJECT_NAME:${{inputs.target_platform}}-latest $IMAGE_NAME:pre-build
            docker image push $IMAGE_NAME:pre-build
            echo "Pushed image $IMAGE_NAME:pre-build"
          fi

  deploying:
    name: Deploying ${{inputs.target_platform}} project
    runs-on:
      labels: ${{inputs.runner_vm}}

    needs: building
    env:
      CI: true
      HOSTS: ${{inputs.servers}}
      PROJECT_NAME: ${{needs.building.outputs.project_name}}
      IMAGE_TAG: ${{needs.building.outputs.image_tag}}
      PORT: ${{inputs.service_port}}
    
    outputs:
      port: ${{steps.deploying.outputs.port}}
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Deploy on Beta Server
        id: deploying
        run: |
          export IMAGE_NAME="${{inputs.ecr_name}}/$PROJECT_NAME"
          
          echo $HOSTS
          echo $PROJECT_NAME
          echo $IMAGE_TAG
          echo $IMAGE_NAME
          echo "port=$PORT" >> "$GITHUB_OUTPUT"
          echo "${{ secrets.BETA_SSH_PRIVATE_KEY }}" > ./aws-key.pem
          chmod 400 ./aws-key.pem

          for HOST in $HOSTS; do
            ssh -o StrictHostKeyChecking=no -i ./aws-key.pem ubuntu@${HOST} '
              set -e
              aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin ${{inputs.ecr_name}}
              docker pull ${{inputs.ecr_name}}/${{needs.building.outputs.project_name}}:${{inputs.target_platform}}-${{needs.building.outputs.image_tag}}
              docker container stop ${{needs.building.outputs.project_name}}-beta || echo "No container to stop"
              docker container rm ${{needs.building.outputs.project_name}}-beta || echo "No container to remove"
              # aws logs create-log-group --log-group-name ${{needs.building.outputs.project_name}}-syslog-beta || echo "Log group already created"
              # docker run -d --log-driver=awslogs --log-opt awslogs-region=sa-east-1 --log-opt awslogs-group=${{needs.building.outputs.project_name}}-syslog-beta -p ${{ needs.building.outputs.port }}:80 --restart always --name ${{needs.building.outputs.project_name}}-beta ${{inputs.ecr_name}}/${{needs.building.outputs.project_name}}:${{inputs.target_platform}}-${{needs.building.outputs.image_tag}}
              docker run -d --network host --restart always --name ${{needs.building.outputs.project_name}}-beta ${{inputs.ecr_name}}/${{needs.building.outputs.project_name}}:${{inputs.target_platform}}-${{needs.building.outputs.image_tag}}
              echo 'Project published successfully on $HOST'
            '
          done
