name: Workflow for Testing

on:
  workflow_dispatch:

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setting SSH
        run: |
          echo ">>> ${{ env.TEST_VAR }}"
